//
//  RandomName.m
//  Reality TV Show Name Generator
//
//  Created by Mollie on 12/6/14.
//  Copyright (c) 2014 Proximity Viz LLC. All rights reserved.
//

#import "RandomName.h"

@implementation RandomName

- (NSArray *) firstNames {
    if (_firstNames == nil) {
        _firstNames = [[NSArray alloc] initWithObjects:@"100 Days of",
                       @"16 and",
                       @"19 Kids and",
                       @"30",
                       @"Action",
                       @"Air",
                       @"Airline",
                       @"Airport",
                       @"All Star",
                       @"Amateur",
                       @"America\'s",
                       @"America\'s Funniest",
                       @"American",
                       @"Amish",
                       @"An American",
                       @"Ancient",
                       @"Army",
                       @"Auction",
                       @"Ax",
                       @"BBQ",
                       @"Bachelor",
                       @"Bachelorette",
                       @"Backyard",
                       @"Bad Girls",
                       @"Baggage",
                       @"Band",
                       @"Bar",
                       @"Basketball",
                       @"Big",
                       @"Boot Camp",
                       @"Bounty",
                       @"Cajun",
                       @"Cake",
                       @"Canadian",
                       @"Candid",
                       @"Casino",
                       @"Castaway",
                       @"Cathouse",
                       @"Celebrity",
                       @"Chef",
                       @"Chopped",
                       @"Chopper",
                       @"Clean",
                       @"College",
                       @"Colonial",
                       @"Combat",
                       @"Comedy",
                       @"Comic",
                       @"Commando",
                       @"Craft",
                       @"Crocodile",
                       @"Dance",
                       @"Dancing",
                       @"Dancing with the",
                       @"Date",
                       @"Diva",
                       @"Dog",
                       @"Dog Eat",
                       @"Drag",
                       @"Drama",
                       @"Duck",
                       @"Empire",
                       @"EXTREME",
                       @"Face",
                       @"Fame",
                       @"Family",
                       @"Farm",
                       @"Fast",
                       @"Fast Food",
                       @"Fat",
                       @"Fear",
                       @"Fish Tank",
                       @"Flying",
                       @"For",
                       @"Forensic",
                       @"Frontier",
                       @"Half Pint",
                       @"Hell\'s",
                       @"Here Comes",
                       @"Holiday",
                       @"Hollywood",
                       @"Home Sweet",
                       @"Hot Rod",
                       @"House",
                       @"Human",
                       @"Ice Road",
                       @"Impractical",
                       @"Intervention",
                       @"Jersey",
                       @"Jerseylicious",
                       @"Job",
                       @"Judge",
                       @"Justice",
                       @"Keeping up with the",
                       @"Kid",
                       @"King of",
                       @"Kitchen",
                       @"Knight",
                       @"LA",
                       @"Life of",
                       @"Logging",
                       @"Love",
                       @"Mega",
                       @"Miami",
                       @"Million Dollar",
                       @"Millionaire",
                       @"Model",
                       @"Modern",
                       @"Mom",
                       @"Most Extreme",
                       @"Most Extreme Elimination",
                       @"Motorway",
                       @"Mountain",
                       @"Music",
                       @"Mystery",
                       @"Myth",
                       @"Naked and",
                       @"Nanny",
                       @"New York",
                       @"Octane",
                       @"Operation",
                       @"Opposite",
                       @"Orange County",
                       @"Outback",
                       @"Paradise",
                       @"Paranormal",
                       @"Parental",
                       @"Pawn",
                       @"Pioneer",
                       @"Pirate",
                       @"Pop",
                       @"Pretty",
                       @"Project",
                       @"Queen of",
                       @"Queer",
                       @"Renovation",
                       @"Restaurant",
                       @"Rich Kids of",
                       @"Road",
                       @"Rock",
                       @"Rock Star",
                       @"Room",
                       @"Royal",
                       @"Ru Paul\'s",
                       @"Scare",
                       @"Shark",
                       @"Shipping",
                       @"Simple",
                       @"Single",
                       @"Sister",
                       @"Snoop Dogg\'s",
                       @"So You Think You Can",
                       @"Sorority",
                       @"Soul",
                       @"Space",
                       @"Spouse",
                       @"Spy",
                       @"Star",
                       @"Storage",
                       @"Style",
                       @"Surf",
                       @"Survival",
                       @"Sweet",
                       @"Teen",
                       @"Temptation",
                       @"Toned",
                       @"The",
                       @"The 1940s",
                       @"The Amazing",
                       @"The Deadliest",
                       @"The Diamond",
                       @"The Great American",
                       @"The Little",
                       @"The Living",
                       @"The People\'s",
                       @"The Real",
                       @"The Real Housewives of",
                       @"This is Your",
                       @"Three",
                       @"Throttle",
                       @"Tool",
                       @"Top",
                       @"Trauma",
                       @"Treasure",
                       @"True",
                       @"Turf",
                       @"UFO",
                       @"Ultimate",
                       @"Undercover",
                       @"Untold Stories of the",
                       @"Voice",
                       @"Warrior",
                       @"Wedding",
                       @"Whale",
                       @"Wife",
                       @"Wild",
                       @"Yard",
                       nil];
    }
    return _firstNames;
}

- (NSArray *) secondNames {
    if (_secondNames == nil) {
        _secondNames = [[NSArray alloc] initWithObjects:
                        @"911",
                        @"Academy",
                        @"Aliens",
                        @"Apprentice",
                        @"Assistant",
                        @"Attack",
                        @"Battles",
                        @"Bachelor",
                        @"Bachelorette",
                        @"Behavior",
                        @"Beverly Hills",
                        @"Blitz",
                        @"Boss",
                        @"Boys",
                        @"Brawlers",
                        @"Brother",
                        @"Camp",
                        @"Cars",
                        @"Casino",
                        @"Casting Call",
                        @"Catch",
                        @"Cathouse",
                        @"Celebrities",
                        @"Challenge",
                        @"Cheaters",
                        @"Chef",
                        @"Chopped",
                        @"Chopper",
                        @"Choppers",
                        @"City",
                        @"Club",
                        @"Collar",
                        @"Comedians",
                        @"Consignment",
                        @"Contender",
                        @"Contest",
                        @"Control",
                        @"Counting",
                        @"Couple",
                        @"Court",
                        @"Crashers",
                        @"Crew",
                        @"Dad",
                        @"Dance",
                        @"Dance Crew",
                        @"Dancing",
                        @"Date",
                        @"Dating",
                        @"Days",
                        @"Diners",
                        @"Disasters",
                        @"Discoveries",
                        @"Doctors",
                        @"Drag Race",
                        @"Dynasty",
                        @"E.R.",
                        @"Eats",
                        @"Exes",
                        @"Experiment",
                        @"Factor",
                        @"Family",
                        @"Farm",
                        @"Fatherhood",
                        @"Fever",
                        @"Fighter",
                        @"Files",
                        @"Garage",
                        @"Girls",
                        @"Goes to College",
                        @"Greenlight",
                        @"Groom",
                        @"Gypsies",
                        @"Haul",
                        @"Hoarders",
                        @"Hollywood",
                        @"Home Videos",
                        @"Honey Boo Boo",
                        @"Hot Rod",
                        @"Hotel",
                        @"Hour",
                        @"House",
                        @"House Party",
                        @"Housewives",
                        @"Hunter",
                        @"Hunters",
                        @"Icon",
                        @"Idol",
                        @"in the City",
                        @"Ink",
                        @"Intervention",
                        @"Inventor",
                        @"Inventors",
                        @"Island",
                        @"Jail",
                        @"Job",
                        @"Jokers",
                        @"Justice",
                        @"Kings",
                        @"Kitchen",
                        @"Ladies",
                        @"Life",
                        @"Listing",
                        @"Loser",
                        @"Love Island",
                        @"Makeover",
                        @"Mania",
                        @"Marvels",
                        @"Master",
                        @"Mates",
                        @"Men",
                        @"Missions",
                        @"Model",
                        @"Mom",
                        @"Moms",
                        @"Monastery",
                        @"Nation",
                        @"New Jersey",
                        @"Next Door",
                        @"Nightmares",
                        @"Ninja",
                        @"Off",
                        @"Office",
                        @"Overhaulin\'",
                        @"Party",
                        @"Patrol",
                        @"People",
                        @"Pickers",
                        @"Pitmasters",
                        @"Pregnant",
                        @"Princess",
                        @"Project",
                        @"Queens",
                        @"Quest",
                        @"Race",
                        @"Raiders",
                        @"Renovators",
                        @"Rent",
                        @"Repo",
                        @"Rescue",
                        @"Restaurant",
                        @"Restoration",
                        @"Reunited",
                        @"Rivals",
                        @"Room",
                        @"Rooms",
                        @"Rules",
                        @"Runway",
                        @"School",
                        @"Search",
                        @"Secrets",
                        @"Ship",
                        @"Shore",
                        @"Show",
                        @"Showdown",
                        @"Song",
                        @"Spaces",
                        @"Star",
                        @"Stars",
                        @"Story",
                        @"Superhero",
                        @"Supermodel",
                        @"Sweep",
                        @"Sweets",
                        @"Tactics",
                        @"Tank",
                        @"Test Kitchen",
                        @"Toddlers",
                        @"Towers",
                        @"Train",
                        @"Treasure",
                        @"Truckers",
                        @"TV",
                        @"Up",
                        @"VIP",
                        @"Videos",
                        @"Voice",
                        @"Warrior",
                        @"Wars",
                        @"Wedding",
                        @"Whisperer",
                        @"Wishes",
                        @"Witness",
                        @"Wives",
                        @"Worlds",
                        @"Wrangler",
                        @"by Jury",
                        @"of Love",
                        @"to Love",
                        nil];
    }
    return _secondNames;
}

- (NSString*) createName {
    int randomFirst = arc4random_uniform(self.firstNames.count);
    int randomSecond = arc4random_uniform(self.secondNames.count);
    return [NSString stringWithFormat:@"%@ %@", [self.firstNames objectAtIndex:randomFirst], [self.secondNames objectAtIndex:randomSecond]];
}

@end
